#pragma config(Sensor, dgtl1,  ,               sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  RightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  leftencoder,    sensorQuadEncoder)
#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma DebuggerWindows("Globals")
#pragma DebuggerWindows("Motors")
#pragma DebuggerWindows("VexLCD")
#pragma DebuggerWindows("debugStream")

void LCDtimer()
{
	string Timepassed;
	displayLCDCenteredString(0,"Time");
	sprintf(Timepassed,"%1.2f%c",time1[T1]/1000.00);
	displayLCDString(1,13,"Secs");
	displayLCDString(1,1,Timepassed);
	wait1Msec(10);
}

int leftdrivespeed[150]; //Records joystick values
int leftdrivesensorvalue[150]; //Records sensor values
int rightdrivesensorvalue[150]; //records more sensor values
int rightdrivespeed[150]; //records more joystick values
int forloop[150];
int noiselesstimer;
int leftside;
int rightside;
int y;
int w;
task main()
{
	SensorValue(leftencoder)=0;
	clearDebugStream();
	clearLCDLine(0);
	clearLCDLine(1);
	clearTimer(T1);
	while(true)
	{
		motor(port1)=vexRT[Ch3];
		motor(port2)=vexRT[Ch3];
		motor(port3)=vexRT[Ch2];
		motor(port10)=vexRT[Ch2];
		leftside=vexRT[Ch3];
		rightside=vexRT[Ch2];
		noiselesstimer=time1(T1)/100.00;
		LCDtimer();
		//recording from here down
		while(noiselesstimer==forloop && (time1[T1] < 15000))
		{
			leftdrivespeed[forloop]=rightside;
			leftdrivesensorvalue[forloop]=SensorValue(leftencoder);
			rightdrivesensorvalue[forloop]=SensorValue(RightEncoder);
			rightdrivespeed[forloop]=leftside;
			forloop=forloop+1;

		}//steaming from here down
		else if(noiselesstimer==152.00)
		{
			writeDebugStreamLine("byte leftdrivespeed[150]={");
			for(w=1;w<16;w++)
			{
				for(y=0;y<10;y++)
				{
					writeDebugStream("%i,",leftdrivespeed[w*y]);
				}
				writeDebugStreamLine("");
			}
			writeDebugStreamLine("};");
			writeDebugStreamLine("");
			writeDebugStreamLine("byte leftdrivesensorvalue[150]={");
			for(w=1;w<16;w++)
			{
				for(y=0;y<10;y++)
				{
					writeDebugStream("%i,",leftdrivesensorvalue[w*y]);
				}
				writeDebugStreamLine("");
			}
			writeDebugStream("};");
			writeDebugStreamLine("byte rightdrivesensorvalue[150]={");
			for(w=1;w<16;w++)
			{
				for(y=0;y<10;y++)
				{
					writeDebugStream("%i,",rightdrivesensorvalue[w*y]);
				}
				writeDebugStreamLine("");
			}
			writeDebugStreamLine("};");
			writeDebugStreamLine("byte rightdrivespeed[150]={");
			for(w=1;w<16;w++)
			{
				for(y=0;y<10;y++)
				{
					writeDebugStream("%i,",rightdrivespeed[w*y]);
				}
				writeDebugStreamLine("");
			}
			writeDebugStreamLine("};");
			writeDebugStreamLine("");
			writeDebugStreamLine("task leftdrive()");
			writeDebugStreamLine("{");
			writeDebugStreamLine("for(int x=0; x<150; x++)");
			writeDebugStreamLine("{");
			writeDebugStreamLine("	while((SensorValue[dgtl1]>100+leftdrivesensorvalue[x]|| SensorValue[dgtl1]<100-leftdrivesensorvalue[x]))//between some range of numbers in relation to the encoder");
			writeDebugStreamLine("{");
			writeDebugStreamLine(" motor(port1)=leftdrivespeed[x];");
			writeDebugStreamLine(" motor(port2)=leftdrivespeed[x];");
			writeDebugStreamLine("}");
			writeDebugStreamLine("}");
			writeDebugStreamLine("}");
			writeDebugStreamLine("");
			writeDebugStreamLine("task rightdrive()");
			writeDebugStreamLine("{");
			writeDebugStreamLine("for(int x=0; x<150; x++)");
			writeDebugStreamLine("{");
			writeDebugStreamLine("	while((SensorValue[dgtl1]>100+leftdrivesensorvalue[x]|| SensorValue[dgtl1]<100-leftdrivesensorvalue[x])) //between some range of numbers in relation to the encoder");
			writeDebugStreamLine("{");
			writeDebugStreamLine(" motor(port3)=rightdrivespeed[x];");
			writeDebugStreamLine(" motor(port10)=rightdrivespeed[x];");
			writeDebugStreamLine("}");
			writeDebugStreamLine("}");
			writeDebugStreamLine("}");
			writeDebugStreamLine("");
			writeDebugStreamLine("task automonous()");
			writeDebugStreamLine("{");
			writeDebugStreamLine("startTask(leftdrive)");
			writeDebugStreamLine("startTask(rightdrive)");
			writeDebugStreamLine("}");
			wait1Msec(1000);
		}
	}
}
